INSERT INTO TAB_TODO(TODO_ID, TITLE, DESCRIPTION, STATE) VALUES (0, 'Cleaning up', 'Everything', 0);
INSERT INTO TAB_TODO(TODO_ID, TITLE, DESCRIPTION, STATE) VALUES (1, 'Buy in', 'milk, honey, bread', 0);
INSERT INTO TAB_TODO(TODO_ID, TITLE, DESCRIPTION, STATE) VALUES (2, 'Beat someone', 'someone like tim', 0);
INSERT INTO TAB_TODO(TODO_ID, TITLE, DESCRIPTION, STATE) VALUES (3, 'Watch movie', 'Der Pate', 1);
INSERT INTO TAB_TODO(TODO_ID, TITLE, DESCRIPTION, STATE) VALUES (4, 'Do sports', 'climb a wall', 2);